### ISSUE TITLE
Ny energi - terminologi

### ISSUE THREAD

**Issue by evelinabe** [progit2-sv/progit2#3]
Hej @chrillof 
Jag tänkte hjälpa till lite här. 

Har börjat med att kolla lite på det som är gjort och anteckna lite i `TRANSLATION_NOTES`

Den här terminologin används hittills: 
Repository = förvar
Remote repository = fjärrförvar
Commit = förbindning/överlämning
Branch = gren

Tänker att förvar känns lite... gammaldags? Eller, det får mig att tänka på fängelser och flyktingförläggningar. Repo är väl det vanligaste att man säger, annars tänker jag mig arkiv eller arkivlåda eller något liknande. Commit brukar man ju också säga, men såg i [översättningen av git](https://github.com/nafmo/git-l10n-sv) att incheckning används där. Kanske lika bra att använda samma?

Terminologi för push och pull behöver läggas till.

Skulle gärna göra lite sånt här småpyssel runt om innan jag börjar med själva översättningen.

**Comment by chrillof** [comment]
Hej!

Kul att du hör av dig!

Håller absolut med om att terminologin är helt åt skogen och det är faktiskt en av anledningarna till att arbetet stannade av.

Min ambition var att få till bra svenska ord för att få ett bra flyt i texten. För en nybörjare så tänker jag att det lätt blir lite överväldigande att lära sig massa engelsk nomenklatur för ett koncept man ännu inte riktigt förstått, om du förstår hur jag tänker.

Om det är en officiell översättning som du länkar till så skall vi här givetvis förhålla oss till samma nomenklatur och språk.

/Christoffer

**Comment by evelinabe** [comment]
Förstår det. Det är svårt att hitta rätt, så lätt att tycka att det låter fånigt på svenska. Men ja, jag tänker som du att det gör det lättare att förstå, det är tillräckligt abstrakta begrepp ändå. Bättre att våga gå vilse lite till en början än att inte ens försöka 😄.

**Comment by evelinabe** [comment]
@chrillof här är en kort sammanfattning av lite olika översättningar jag har hittat här och i git:

Repository = förvar (här)/ arkiv (i git)
Remote repository = fjärrförvar
Commit = förbindning (här)/incheckning (git)
Branch = gren
Push = överlämna (här)/sända (git)
Merge = slå samman
Fetch = hämta
Rebase = ombasera 
Worktree = arbetskatalog
Stage = Kö
Directory = katalog

Massor som saknas såklart, men kan vara bra att börja så här. Spontant så har jag svårt för översättningarna av push - jag gillar tanken på att översätta det rakt av till knuff - att det är ett kommando för att knuffa iväg det man har checkat in till nånannanstans. 

Rebase... Ombasera låter så militäriskt för mig. Jag tänker på "ympa" men det kanske är för att jag är trädgårdsmänniska. 

Kö för stage... Har nog aldrig tänkt på stage som en kö utan som en scen eller hållplats för de dokumenten jag har jobbat i... 

Är öppen för debatt 😀

**Comment by chrillof** [comment]
Tycker det överlag låter bra. Som sagt, jag tycker man bör gå på det som finns i den officiella översättningen som du har kollat på. Baserat på dina förslag så tycker jag att följande översättningar är närmast självskrivna:

- Repository = arkiv
- Remote repository = fjärrarkiv
- Commit = incheckning (här kanske man kan prata om version också?)
- Branch = gren

Utöver dessa tycker jag att dessa funkar:

- Push = skicka
- Fetch = hämta

just eftersom de är näst intill analoga med de engelska verben och beskriver händelseförloppet. Ordagrannt så blir ju _push_ faktiskt _knuff_, men jag tycker att det i sammanhanget blir lite otydligt att det rör sig om att man skickar något någonstans, vilket det rör sig om här.

Utöver dessa tycker jag resten är lite besvärligare:

- Merge = slå samman
  Kanske skall man säga _fusionera_? Då blir det ett verb, precis som i engelskan och det beskriver ju händelseförloppet ganska bra.
- Rebase = ombasera
  Detta är väldigt svåröversatt tycker jag. Ombasera låter krystat, men hittade inget annat ord. Ympa vet jag att jag läste någonstans men det känns också lite för botaniskt, hehe 😄 Jag skulle nog heller aldrig i mitt dagliga arbete säga "ombasera"...
- Worktree = arbetskatalog
  Denna fungerar väl hyfsat tycker jag, men man kanske skall säga _arbetsyta_ istället? Jag har för mig att jag gjort den översättningen på vissa ställen, men kan ha fel för mig.
- Stage = Kö
  Håller helt med dig om att man inte bör blanda in kö här, eftersom det ju faktiskt kan förväxlas med datatypen. Tycker även denna är lite besvärlig. Det är också en av de koncept som jag upplever att många har lite svårt att greppa i början. Speciellt när man är van vid en del andra centrala versionshanteringssystem. Här hade jag tidigare översättningen "förberedda ytan" men det lät så otroligt skitnödigt att jag tror att jag fimpade det på de flesta ställen. Man får nog fundera lite på hur det används i Git. Kanske _förteckning_? När du gör `git add` så uppdaterar man ju förteckningen över vad som skall ingå i nästa incheckning? Scen eller hållplats kanske också fungerar. Man skulle behöva en exempelmening för att höra vad som känns bäst.
- Directory = katalog
  Man skulle också kunna säga _mapp_...

Det var väl mina tankar för dagen 🤔

**Comment by chrillof** [comment]
Tänkte lite till:

**Merge**
Förslag: _fusionera_, _förena_, eller _kombinera_

**Rebase**
Förslag: _flytta_

**Comment by chrillof** [comment]
Det finns en gammal wikisida som heter "nyckelbegrepp". Jag uppdaterar den med lite av det vi kommit fram till här. Eller finns det något bättre sätt, tänker du?

**Comment by evelinabe** [comment]
Jag har sett en sån här flik för diskussioner på vissa repon, kanske är bra för att inte alltid behöva skapa en issue? Filen `TRANSLATION_NOTES.asc`kan fyllas på också. 
<img width="1370" alt="bild" src="https://github.com/progit2-sv/progit2/assets/19805312/45c16b1a-5ccd-48bf-ba56-8f6c95224119">

**Comment by chrillof** [comment]
Se där! Nu lyckades jag lägga till det 😄 Då kan vi köra vidare diskussionen där så stänger jag detta ärendet.
